<a href="https://colab.research.google.com/github/utku-ozcan/Machine_Learning/blob/main/MachineLearningFundamentals_MainProject_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow import keras
from keras.models import Sequential
from keras.datasets import mnist
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout
from keras.optimizers import SGD, Adam, RMSprop
from keras.datasets import cifar10
from keras.utils import to_categorical
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
from keras.layers import Convolution2D
import cv2
from keras.layers import Conv2D
from keras.layers import MaxPool2D, MaxPooling2D
import os
import pandas as pd
from keras import regularizers


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
y_train = np.genfromtxt("/content/drive/MyDrive/Colab_Notebooks/y_train.csv",delimiter=",")

In [ ]:
y_train = y_train[1:]
y_train

array([[0.0000e+00, 0.0000e+00],
       [1.0000e+00, 1.0000e+00],
       [2.0000e+00, 0.0000e+00],
       ...,
       [1.6179e+04, 2.0000e+00],
       [1.6180e+04, 0.0000e+00],
       [1.6181e+04, 1.0000e+00]])

In [ ]:
!unzip "/content/drive/MyDrive/Colab_Notebooks/train_data_unlabeled.zip" -d "./train_data"

In [ ]:
!ls "./train_data/train_data_unlabeled"

In [ ]:
x_train = '/content/train_data/train_data_unlabeled'

In [ ]:
imagefiles_train = os.listdir(x_train)
imagefiles_train = sorted(imagefiles_train, key = lambda x:int(x.split("_")[1][:-4]))

In [ ]:
imagefiles_train

In [ ]:
images_train = []
for i in range(len(imagefiles_train)):
  new_image = cv2.imread("/content/train_data/train_data_unlabeled/" + imagefiles_train[i])
  images_train.append(new_image)

In [ ]:
images_train

In [ ]:
np.asarray(images_train).shape

(16182, 45, 51, 3)

In [ ]:
!unzip "/content/drive/MyDrive/Colab_Notebooks/test_data_unlabeled.zip" -d "./test_data"

In [ ]:
!ls "./test_data/test_data_unlabeled"

In [ ]:
x_test = '/content/test_data/test_data_unlabeled'

In [ ]:
imagefiles_test = os.listdir(x_test)
imagefiles_test = sorted(imagefiles_test, key = lambda x:int(x.split("_")[1][:-4]))

In [ ]:
images_test = []
for i in range(len(imagefiles_test)):
  new_image = cv2.imread("/content/test_data/test_data_unlabeled/" + str(imagefiles_test[i]))
  images_test.append(new_image)

In [ ]:
images_test

In [ ]:
np.asarray(images_test).shape

(4796, 45, 51, 3)

In [ ]:
x_data_train = np.asarray(images_train)
x_data_test = np.asarray(images_test)
y_data_train = np.asarray(y_train)

# ***Preprocessing ***

In [ ]:
x_data_train

In [ ]:
y_data_train

array([[0.0000e+00, 0.0000e+00],
       [1.0000e+00, 1.0000e+00],
       [2.0000e+00, 0.0000e+00],
       ...,
       [1.6179e+04, 2.0000e+00],
       [1.6180e+04, 0.0000e+00],
       [1.6181e+04, 1.0000e+00]])

In [ ]:
labels = {0:'0',1:'1',2:'2',3:'3'}
num_classes = 4

In [ ]:
X_train_1 = x_data_train.astype('float32') / 255.0
y_train_1 = to_categorical(y_data_train[:,1], num_classes=4)
X_test_1 = x_data_test.astype('float32') / 255.0

In [ ]:
model = Sequential()

model.add(Conv2D(64, kernel_size=(3, 3), input_shape=(45, 51, 3), activation='relu', padding='same'))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(Conv2D(128, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(Conv2D(256, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes, activation='softmax'))



In [ ]:
optimizer = Adam(learning_rate=0.001)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_68 (Conv2D)          (None, 45, 51, 64)        1792      
                                                                 
 conv2d_69 (Conv2D)          (None, 45, 51, 64)        36928     
                                                                 
 max_pooling2d_36 (MaxPooli  (None, 22, 25, 64)        0         
 ng2D)                                                           
                                                                 
 dropout_38 (Dropout)        (None, 22, 25, 64)        0         
                                                                 
 conv2d_70 (Conv2D)          (None, 22, 25, 128)       73856     
                                                                 
 conv2d_71 (Conv2D)          (None, 22, 25, 128)       147584    
                                                     

In [ ]:
history = model.fit(X_train_1, y_train_1, epochs=50, batch_size=128, validation_split = 0.2)

Epoch 1/50
102/102 [==============================] - 11s 79ms/step - loss: 1.1350 - accuracy: 0.4641 - val_loss: 0.7154 - val_accuracy: 0.7118
Epoch 2/50
102/102 [==============================] - 8s 77ms/step - loss: 0.5164 - accuracy: 0.7917 - val_loss: 0.3393 - val_accuracy: 0.8730
Epoch 3/50
102/102 [==============================] - 7s 73ms/step - loss: 0.3426 - accuracy: 0.8646 - val_loss: 0.2506 - val_accuracy: 0.9027
Epoch 4/50
102/102 [==============================] - 8s 76ms/step - loss: 0.2561 - accuracy: 0.9000 - val_loss: 0.1957 - val_accuracy: 0.9252
Epoch 5/50
102/102 [==============================] - 8s 75ms/step - loss: 0.2016 - accuracy: 0.9210 - val_loss: 0.1943 - val_accuracy: 0.9228
Epoch 6/50
102/102 [==============================] - 8s 76ms/step - loss: 0.1785 - accuracy: 0.9305 - val_loss: 0.1587 - val_accuracy: 0.9410
Epoch 7/50
102/102 [==============================] - 8s 76ms/step - loss: 0.1627 - accuracy: 0.9371 - val_loss: 0.1286 - val_accuracy: 0.950

In [ ]:
all_predictions = model.predict(X_test_1)
all_predictions_list = all_predictions.tolist()
all_predictions.tolist()

In [ ]:
all_predictions = model.predict(X_test_1)
output = []

for prediction in all_predictions:
    max_index = np.where(prediction == np.max(prediction))[0][0]
    output.append(max_index)

print(output)
print(len(output))

In [ ]:
first_column = np.arange(len(output))

result_array = np.column_stack((first_column, output))
print(result_array)

header_row = 'id,target'
np.savetxt('/content/drive/MyDrive/output.csv', result_array, delimiter=',', fmt='%d', header=header_row, comments='')

[[   0    1]
 [   1    3]
 [   2    3]
 ...
 [4793    0]
 [4794    0]
 [4795    2]]
